/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["AppController_healthy"];
  };
  "/users": {
    get: operations["UsersController_find"];
    post: operations["UsersController_create"];
  };
  "/users/login": {
    post: operations["UsersController_login"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Profile: {
      name?: string;
      lastname?: string;
    };
    CreateUserDto: {
      email: string;
      password: string;
      profile: components["schemas"]["Profile"];
    };
    User: {
      _id?: string;
      email?: string;
      profile?: components["schemas"]["Profile"];
    };
    FindUserDto: {
      users: components["schemas"]["User"][];
    };
    LoginDto: {
      email: string;
      password: string;
    };
    UserTokenDto: {
      token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_healthy: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UsersController_find: {
    parameters: {
      query?: {
        count?: number;
        page?: number;
        fields?: string;
        q?: string;
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["FindUserDto"];
        };
      };
    };
  };
  UsersController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["FindUserDto"];
        };
      };
    };
  };
  UsersController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      default: {
        content: {
          "application/json": components["schemas"]["UserTokenDto"];
        };
      };
    };
  };
}
