import { Navbar } from "../../shared/components/Navbar/Navbar";
import type { Metadata } from "next";
import '@fortawesome/fontawesome-free/css/all.min.css'
import "../globals.scss";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};


export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}