import { Navbar } from "../../shared/components/Navbar/Navbar";
import type { Metadata } from "next";
import '@fortawesome/fontawesome-free/css/all.min.css'
import "../globals.scss";
import { NavigationData } from "./providers/server/navigations";

export const metadata: Metadata = {
  title: "Shippings",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const data = await NavigationData();

  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Navbar links={data?.sort((a, b) => (a.attributes?.order || 0) - (b.attributes?.order || 0))} />
          <div className="main w-full h-screen overflow-auto py-5 px-10 pb-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}